In [28]:

import numpy as np

# creating an array

arr1 = np.array([1, 2, 3,4,5])
print (arr1)
print(type(arr1))
print(arr1.shape)

arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])

print(arr2[1:, 1:3])


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[[ 7  8]
 [12 13]]


In [ ]:
#1. Create a 1D array of even numbers from 2 to 20 (inclusive).
#2. Create a 3×3 array of all zeros, then change its dtype to float32. (Hint: check the dtype parameter in np.zeros)

arr_even = np.arange(2, 22, 2)
print(arr_even)

mul_dim_arr = np.zeros((3, 3), dtype=np.float32)
print(mul_dim_arr.dtype)

[ 2  4  6  8 10 12 14 16 18 20]
float64


TypeError: 'numpy.dtypes.Float64DType' object is not callable